-- CreateTable
CREATE TABLE "Application" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "counterparty" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "regName" TEXT NOT NULL,
    "regDate" TEXT NOT NULL,
    "regCountry" TEXT NOT NULL,
    "regId" TEXT NOT NULL,
    "regAddr" TEXT NOT NULL,
    "bsnsAddr" TEXT NOT NULL,
    "telephone" TEXT NOT NULL,
    "website" TEXT NOT NULL,
    "bankName" TEXT NOT NULL,
    "bankAddr" TEXT NOT NULL,
    "country" TEXT NOT NULL,
    "accNum" TEXT NOT NULL,
    "swiftCode" TEXT NOT NULL,
    "iban" TEXT NOT NULL,
    "accBen" TEXT NOT NULL,
    "certOfInc" TEXT NOT NULL,
    "cr14" TEXT NOT NULL,
    "cr6" TEXT NOT NULL,
    "maa" TEXT NOT NULL,
    "ids" TEXT NOT NULL,
    "proofOfRes" TEXT NOT NULL,
    "taxClearance" TEXT NOT NULL,
    "benOwnership" TEXT NOT NULL,
    "resolutionAuth" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "status1" TEXT NOT NULL
);
